### ISSUE TITLE
Migrar do github para o gitlab eliminindo dependência do travis

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/do_zero_a_implantantacao#21]
prós:

- ci integrado
- permite python 3.7

contra:

- não é a ferramenta mais comum/famosa

**Comment by nilold** [comment]
Essa issue ainda é válida, dado que agora existe o Actions?

**Comment by cassiobotaro** [comment]
Não, antigamente o travis tinha problemas com a versão corrente do python que era 3.7, mas isso já foi resolvido. Vou fechar a issue.
